@startuml
package "BusinessRules" #FFF {
  package "Entity" #EEEEEE {
    class Enterprise{
          * product_id : INTEGER
          -- name : String
          -- price : MONEY
    }
    class establishment
    class Enterprise
  }
 }
@enduml
